### ISSUE TITLE
Crash after splashscreen when starting on macOS

### ISSUE THREAD

**Issue by mtt-ableton** [ownbee/doorstop-edit#4]
**Checklist:**

- [x] I updated to the latest version available
- **Last working release (if known):** not known

**Description of problem:**

Briefly shows splashscreen, then crashes on startup. macOS crash dialog shows this text: see attached [crash.txt](https://github.com/ownbee/doorstop-edit/files/12841599/crash.txt)

Terminal shows:
```
$ doorstop-edit
qt.qpa.fonts: Populating font family aliases took 230 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost. 
Segmentation fault: 11
```

**Version dump:**

```
$ doorstop-edit --version
qt.qpa.fonts: Populating font family aliases took 230 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost. 
Version: 0.1.1
VCS: cdf3404
Commit: cdf3404edfd1d60ef6d1236b3b444cffb7a77b75
Date: 2023-01-18T20:03:04.408372
Doorstop: 2.2.1
PySide6: 6.5.2
Python: 3.11.5
OS: macOS-13.3-arm64-arm-64bit
Traceback (most recent call last):
  File "/opt/homebrew/bin/doorstop-edit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/doorstop_edit/main.py", line 117, in main
    app.aboutToQuit.connect(editor.quit)  # type: ignore
                            ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'quit'
```

**Additional information:**

**Comment by ownbee** [comment]
I own no mac so I cannot fix it. Contributions fixing this is appreciated.
